// app/metadata.ts
import type { Metadata } from "next"; // Use Metadata type from Next.js

export const metadata: Metadata = {
  title: "Kara Aya Architecture",
  description: "Atelier d'architecture à Tangier, Maroc...",
  icons: [
    {
      media: "(prefers-color-scheme: light)",
      url: "/icondark.ico", // Use `url` instead of `href`
    },
    {
      media: "(prefers-color-scheme: dark)",
      url: "/iconlight.ico",
    },
  ],
  metadataBase: new URL("http://localhost:3000"),
  keywords: [
    "Architecture Tangier", 
    "Architecture à Tanger", 
    "الهندسة المعمارية في طنجة",
    "Architecture firm Morocco", 
    "Cabinet d’architecture au Maroc", 
    "مكتب الهندسة المعمارية في المغرب",
    "Urban planning Northern Morocco", 
    "Urbanisme au nord du Maroc", 
    "التخطيط الحضري في شمال المغرب",
    "Interior design Tangier", 
    "Design intérieur à Tanger", 
    "تصميم داخلي في طنجة",
    "Building Information Modeling Morocco", 
    "Modélisation des données du bâtiment Maroc", 
    "نمذجة معلومات البناء في المغرب",
    "Scenography services Morocco", 
    "Services de scénographie au Maroc", 
    "خدمات تصميم المشاهد في المغرب",
    "Exterior renovation Morocco", 
    "Rénovation extérieure au Maroc", 
    "ترميم خارجي في المغرب",
    "Project management assistance Morocco", 
    "Assistance à la gestion de projets au Maroc", 
    "مساعدة إدارة المشاريع في المغرب",
    "Free architectural consultations Morocco", 
    "Consultations architecturales gratuites au Maroc", 
    "استشارات معمارية مجانية في المغرب",
    "Sustainable architecture Morocco", 
    "Architecture durable au Maroc", 
    "الهندسة المعمارية المستدامة في المغرب",
    "Experienced architects in Tangier", 
    "Architectes expérimentés à Tanger", 
    "مهندسون معماريون ذوو خبرة في طنجة",
    "Custom home design Morocco", 
    "Conception de maison sur mesure au Maroc", 
    "تصميم المنازل حسب الطلب في المغرب",
    "Urban development strategies Morocco", 
    "Stratégies de développement urbain au Maroc", 
    "استراتيجيات التنمية الحضرية في المغرب",
    "Luxury interior design Morocco", 
    "Design intérieur de luxe au Maroc", 
    "تصميم داخلي فاخر في المغرب",
    "Architectural design services Tangier", 
    "Services de conception architecturale à Tanger", 
    "خدمات التصميم المعماري في طنجة",
    "Northern Morocco architecture firm", 
    "Cabinet d’architecture au nord du Maroc", 
    "مكتب الهندسة المعمارية في شمال المغرب",
    "Best architects in Tangier", 
    "Meilleurs architectes à Tanger", 
    "أفضل المهندسين المعماريين في طنجة",
    "Architecture services in Morocco", 
    "Services d'architecture au Maroc", 
    "خدمات الهندسة المعمارية في المغرب"
  ]};
